controller_list:
 - name: /thor_mang/head_traj_controller
   action_ns: follow_joint_trajectory
   type: FollowJointTrajectory
   default: true
   joints:
      - head_pan
      - head_tilt    
 
 - name: /thor_mang/torso_traj_controller
   action_ns: follow_joint_trajectory
   type: FollowJointTrajectory
   default: true
   joints:
      - waist_pan
      - waist_tilt    
 
 - name: /thor_mang/left_arm_traj_controller
   action_ns: follow_joint_trajectory
   type: FollowJointTrajectory
   default: true
   joints:
      - l_shoulder_pitch
      - l_shoulder_roll
      - l_shoulder_yaw
      - l_elbow
      - l_wrist_yaw1
      - l_wrist_roll
      - l_wrist_yaw2
       
 - name: /thor_mang/right_arm_traj_controller
   action_ns: follow_joint_trajectory
   type: FollowJointTrajectory
   default: true
   joints:
      - r_shoulder_pitch
      - r_shoulder_roll
      - r_shoulder_yaw
      - r_elbow
      - r_wrist_yaw1
      - r_wrist_roll
      - r_wrist_yaw2
      