<?xml version="1.0"?>

<robot name="hector_centaur" xmlns:xacro="http://www.ros.org/wiki/xacro">

  <!-- Included URDF Files -->
  <xacro:include filename="$(find hector_tracked_vehicles_description)/urdf/obelix_ugv_standalone.urdf.xacro" />
  
  
  <joint
    name="base_to_pelvis_joint"
    type="fixed">
    <origin
      xyz="0.0 0 0.3"
      rpy="0 0 0"
       />
    <!--rpy="0.000329950722368627 -3.91151844547536E-19 1.16573417585641E-15"-->
    <parent
      link="base_link" />
    <child
      link="pelvis" />
    <!--
    <axis
      xyz="0 0 1" />
    <xacro:joint_medium_servo_limits_macro lower="${-1.8}" upper="${1.3}"/>
    -->
  </joint>
  
  
  

  <xacro:include filename="$(find thor_mang_description)/urdf/constants.xacro" />

  <!--<xacro:include filename="$(find thor_mang_description)/urdf/thor_mang_simple_mesh_visual_geoms.urdf.xacro.xml" />    -->
  <xacro:include filename="$(find thor_mang_description)/urdf/thor_mang_mesh_visual_geoms.urdf.xacro.xml" />

  <xacro:include filename="$(find thor_mang_description)/urdf/thor_mang_primitive_collision_geoms.urdf.xacro.xml" />
  <!--<xacro:include filename="$(find thor_mang_description)/urdf/thor_mang_mesh_collision_geoms.urdf.xacro.xml" />    -->
  
  <xacro:include filename="$(find thor_mang_description)/urdf/thor_poking_stick.urdf.xacro" />
  <xacro:include filename="$(find thor_mang_description)/urdf/arm/thor_arm_7dof_simple.urdf.xacro" />
  <xacro:include filename="$(find thor_mang_description)/urdf/torso/thor_mang_torso.urdf.xacro.xml" />
  <xacro:include filename="$(find thor_mang_description)/urdf/leg/thor_mang_leg.urdf.xacro.xml" />
  
  
  <xacro:include filename="$(find thor_mang_description)/urdf/head/thor_head_pan_tilt_unit.urdf.xacro.xml" />
  <xacro:include filename="$(find thor_mang_description)/urdf/head/thor_$(optenv THOR_HEAD_TYPE hector_multisensor)_head.urdf.xacro.xml" />
  <xacro:include filename="$(find thor_mang_description)/urdf/lidar/thor_lidar_pan_unit.urdf.xacro.xml" />
  
  <!--<xacro:include filename="$(find thor_mang_description)/robots/offsets/thor_mang_tud_joint_offsets.urdf.xacro.xml" /-->>
  <xacro:include filename="$(find thor_mang_description)/robots/offsets/thor_mang_zero_offsets.urdf.xacro.xml" />     
  
<!--  <macro name="thor_mang_tud_simple_macro">-->
  
  <thor_mang_torso_macro />
  
  <!--  
  <thor_mang_leg_macro parent="pelvis" name="l" reflect="1" leg_joint3_limit_lower="${-M_PI*0.15}" leg_joint3_limit_upper="${M_PI}">
    <origin xyz="0.0 0.072 -0.145" rpy="0 0 0"/>
  </thor_mang_leg_macro>
  
  <thor_mang_leg_macro parent="pelvis" name="r" reflect="-1" leg_joint3_limit_lower="${-M_PI}" leg_joint3_limit_upper="${M_PI*0.15}">
    <origin xyz="0.0 -0.072 -0.145" rpy="0 0 0"/>
  </thor_mang_leg_macro>
  
  <thor_poking_stick_macro parent="utorso">    
    <origin xyz="0.185 0.130 0.224" rpy="0 ${0 + l_arm_j0_offset} 0"/>
  </thor_poking_stick_macro>
  -->
  
   <!-- lower3 -M_PI  upper3 M_PI*0.1 --> <!-- limit_6 could be -M_PI*1.3 -->
  <thor_arm_7dof_simple_with_offsets_macro parent="utorso" name="l" reflect="1"
        
     arm_joint_0_limit_lower="${-M_PI}"
     arm_joint_0_limit_upper="${2.3}"
     arm_joint_1_limit_lower="${-M_PI}"
     arm_joint_1_limit_upper="${0.05}" 
     arm_joint_2_limit_lower="${-M_PI*0.5}"
     arm_joint_2_limit_upper="${M_PI}" 
     arm_joint_3_limit_lower="${-2.9}" 
     arm_joint_3_limit_upper="${0.6}"
     arm_joint_4_limit_lower="${-M_PI}"
     arm_joint_4_limit_upper="${4.71}"  
     arm_joint_5_limit_lower="${-1.47}"   
     arm_joint_5_limit_upper="${1.47}"   
     arm_joint_6_limit_lower="${-2.54}"   
     arm_joint_6_limit_upper="${0.9}"
                           
     j1_offset="${l_arm_j1_offset}"
     j2_offset="${l_arm_j2_offset}"
     j3_offset="${l_arm_j3_offset}"
     j4_offset="${l_arm_j4_offset}"
     j5_offset="${l_arm_j5_offset}"
     j6_offset="${l_arm_j6_offset}">    
    <origin xyz="0.0 0.234 0.165" rpy="0 ${0 + l_arm_j0_offset} 0"/>
  </thor_arm_7dof_simple_with_offsets_macro>
 
  <thor_arm_7dof_simple_with_offsets_macro parent="utorso" name="r" reflect="-1"
     arm_joint_0_limit_lower="${-2.3}"
     arm_joint_0_limit_upper="${M_PI}"
     arm_joint_1_limit_lower="${-0.05}"
     arm_joint_1_limit_upper="${M_PI}" 
     arm_joint_2_limit_lower="${-M_PI}"
     arm_joint_2_limit_upper="${M_PI*0.5}" 
     arm_joint_3_limit_lower="${-0.6}" 
     arm_joint_3_limit_upper="${2.9}"
     arm_joint_4_limit_lower="${-4.71}"
     arm_joint_4_limit_upper="${M_PI}"  
     arm_joint_5_limit_lower="${-1.47}"   
     arm_joint_5_limit_upper="${1.47}"   
     arm_joint_6_limit_lower="${-0.9}"   
     arm_joint_6_limit_upper="${2.54}"

     j1_offset="${r_arm_j1_offset}"
     j2_offset="${r_arm_j2_offset}"
     j3_offset="${r_arm_j3_offset}"
     j4_offset="${r_arm_j4_offset}"
     j5_offset="${r_arm_j5_offset}"
     j6_offset="${r_arm_j6_offset}">    
    <origin xyz="0.0 -0.234 0.165" rpy="0 ${0 + r_arm_j0_offset} 0"/>
  </thor_arm_7dof_simple_with_offsets_macro>
  
  <thor_head_pan_tilt_unit_macro parent="utorso" name="head" head_link_name="head_link"
     j1_offset="${head_j1_offset}">
    <origin xyz="0.0 0.0 0.320" rpy="0 ${0 + head_j0_offset} 0"/>
  </thor_head_pan_tilt_unit_macro>
  
  <thor_head_macro />  
  <!--  
  <thor_lidar_pan_unit_macro parent="utorso" name="waist">
    <origin xyz="0.05 0.0 0.08" rpy="0 0 0"/>
  </thor_lidar_pan_unit_macro>
  -->
  
  <xacro:include filename="$(find thor_mang_description)/hands/$(optenv RIGHT_HAND_TYPE l_vt_hand).urdf.xacro" />
  <xacro:include filename="$(find thor_mang_description)/hands/$(optenv LEFT_HAND_TYPE  r_vt_hand).urdf.xacro" />
  
  <gazebo>
    <plugin name="gazebo_ros_control" filename="libgazebo_ros_control.so">
      <robotNamespace>thor_mang</robotNamespace>
    </plugin>
  </gazebo>
<!--</macro>-->
  
  
    <xacro:include filename="$(find hector_components_description)/urdf/vision_box_common_dimensions.urdf.xacro" />
    <xacro:include filename="$(find hector_components_description)/urdf/vision_box_dimensions_hector2.urdf.xacro" />
    <xacro:include filename="$(find hector_sensors_description)/urdf/hokuyo_utm30lx.urdf.xacro" />
    <joint name="laser1/x" type="revolute">
      <origin xyz="${x_vision_box_front} 0 0.2" rpy="0 0 0"/>
      <parent link="base_link"/>
      <child link="laser1RollServo"/>
      <axis xyz="1 0 0"/>
      <limit lower="${-M_PI/2}" upper="${M_PI/2}" effort="100" velocity="100"/>
    </joint>
    
    <link name="laser1RollServo">
      <inertial_sphere mass="0.1" diameter="0.07"/>
      <visual>
        <origin xyz="${laser1RollServo_size_x/2} 0.0 0.0" rpy="0 0 0"/>
        <geometry>
          <box size="${laser1RollServo_size_x} ${laser1RollServo_size_y} ${laser1RollServo_size_z}"/>
        </geometry>
        <material name="Blue"/>
      </visual>
      <collision>
        <origin xyz="${laser1RollServo_size_x/2} 0.0 0.0" rpy="0 0 0"/>
        <geometry>
          <box size="${laser1RollServo_size_x} ${laser1RollServo_size_y} ${laser1RollServo_size_z}"/>
        </geometry>
      </collision>
    </link>
    
    <joint name="laser1/y" type="revolute">
      <origin xyz="${laser1RollServo_size_x} 0 0" rpy="0 0 0"/>
      <parent link="laser1RollServo"/>
      <child link="laser1_link"/>
      <axis xyz="0 1 0"/>
      <limit lower="${-M_PI/2}" upper="${M_PI/2}" effort="100" velocity="100"/>
    </joint>
    
    <link name="laser1_link">
      <inertial_sphere mass="0.1" diameter="0.07"/>
      <visual>
        <origin xyz="0.0 0.0 ${laser1_size_z/2}" rpy="0 0 0"/>
        <geometry>
          <!--<box size="${laser1_size_x} ${laser1_size_y} ${laser1_size_z}" />-->
          <box size="${laser1_size_x} ${laser1_size_y} 0.01"/>
        </geometry>
        <material name="Grey"/>
      </visual>
      <collision>
        <origin xyz="0.0 0.0 ${laser1_size_z/2}" rpy="0 0 0"/>
        <geometry>
          <!--<box size="${laser1_size_x} ${laser1_size_y} ${laser1_size_z}" />-->
          <box size="${laser1_size_x} ${laser1_size_y} 0.01"/>
        </geometry>
      </collision>
    </link>
    
    <xacro:hokuyo_utm30lx name="laser1" parent="laser1_link" ros_topic="/laser1/scan_no_intensities_from_gazebo" update_rate="40" ray_count="1081" min_angle="135" max_angle="-135">
      <origin xyz="${laser1_center_x_offset} 0 ${laser1_plane_height}" rpy="0 0 0"/>
    </xacro:hokuyo_utm30lx>
    
    <gazebo>    
      <plugin name="laser1_servo_controller" filename="libhector_servo_plugin.so">
        <alwaysOn>true</alwaysOn>
        <controlRate>50.0</controlRate>
        <updateRate>0.0</updateRate>
        <firstServoName>laser1/x</firstServoName>
        <firstServoAxis>1 0 0</firstServoAxis>
        <secondServoName>laser1/y</secondServoName>
        <secondServoAxis>0 1 0</secondServoAxis>
        <torque>0.5</torque>
        <robotNamespace>/</robotNamespace>
        <topicName>laser1/command</topicName>
        <jointStateName>joint_states</jointStateName>
        <proportionalControllerGain>8.0</proportionalControllerGain>
        <derivativeControllerGain>0.0</derivativeControllerGain>
        <maxVelocity>0.0</maxVelocity>
      </plugin>
    </gazebo>
      
    
    
    
    
    
    
    <joint name="camera/z" type="revolute">
      <origin xyz="0.2 0 0.24" rpy="0 0 0"/>
      <parent link="base_link"/>
      <child link="cameraYawServo"/>
      <axis xyz="0 0 1"/>
      <limit lower="${-M_PI*3/4}" upper="${M_PI*3/4}" effort="100" velocity="100"/>
    </joint>
    
    <link name="cameraYawServo">
      <inertial_sphere mass="0.1" diameter="0.07"/>
      <visual>
        <origin xyz="0.0 0.0 ${cameraYawServo_size_z/2}" rpy="0 0 0"/>
        <geometry>
          <box size="${cameraYawServo_size_x} ${cameraYawServo_size_y} ${cameraYawServo_size_z}"/>
        </geometry>
        <material name="Blue"/>
      </visual>
      <collision>
        <origin xyz="0.0 0.0 ${cameraYawServo_size_z/2}" rpy="0 0 0"/>
        <geometry>
          <box size="${cameraYawServo_size_x} ${cameraYawServo_size_y} ${cameraYawServo_size_z}"/>
        </geometry>
      </collision>
    </link>
    
    <joint name="camera/y" type="revolute">
      <origin xyz="0 0 ${cameraYawServo_size_z}" rpy="0 0 0"/>
      <parent link="cameraYawServo"/>
      <child link="mounting_link"/>
      <axis xyz="0 1 0"/>
      <limit lower="${-M_PI/2}" upper="${M_PI/2}" effort="100" velocity="100"/>
    </joint>
    
    <link name="mounting_link">
      <inertial_sphere mass="0.05" diameter="0.07"/>
    </link>
    
    <xacro:include filename="$(find hector_sensors_description)/urdf/thermaleye_camera.urdf.xacro"/>
      
    <xacro:thermaleye_camera_model name="infrared" parent="mounting_link">
      <origin xyz="${infrared_x_position} ${infrared_y_position} ${infrared_z_position}" rpy="0 0 0"/>
    </xacro:thermaleye_camera_model>
    
    <xacro:asus_camera_model name="openni" parent="mounting_link">
      <origin xyz="${kinect_x_position} ${kinect_y_position}  ${kinect_z_position}" rpy="${kinect_roll_position} ${kinect_pitch_position} ${kinect_yaw_position}"/>
    </xacro:asus_camera_model>
    
    <gazebo>
      <plugin name="camera_servo_controller" filename="libhector_servo_plugin.so">
        <alwaysOn>true</alwaysOn>
        <controlRate>50.0</controlRate>
        <updateRate>0.0</updateRate>
        <firstServoName>camera/z</firstServoName>
        <firstServoAxis>0 0 1</firstServoAxis>
        <secondServoName>camera/y</secondServoName>
        <secondServoAxis>0 1 0</secondServoAxis>
        <torque>0.5</torque>
        <robotNamespace>/</robotNamespace>
        <topicName>camera/command</topicName>
        <jointStateName>joint_states</jointStateName>
        <proportionalControllerGain>8.0</proportionalControllerGain>
        <derivativeControllerGain>0.0</derivativeControllerGain>
        <maxVelocity>2.0</maxVelocity>
      </plugin>
    </gazebo>
    
    
    <gazebo reference="openni_depth_frame">
      <sensor type="depth" name="kinect_camera">
        <update_rate>10</update_rate>
        
        <camera>
          <horizontal_fov>${60.0*M_PI/180.0}</horizontal_fov>
          <image>
            <format>R8G8B8</format>
            <width>320</width>
            <height>240</height>
          </image>
          <clip>
            <near>0.05</near>
            <far>3</far>
          </clip>
        </camera>
        
        <plugin name="kinect_camera_controller" filename="libgazebo_ros_openni_kinect.so">
          <alwaysOn>true</alwaysOn>
          <updateRate>10</updateRate>
          <imageTopicName>openni/rgb/image_color</imageTopicName>
          <cameraInfoTopicName>openni/camera_info</cameraInfoTopicName>
          <depthImageTopicName>openni/depth/image_raw</depthImageTopicName>
          <depthImageCameraInfoTopicName>openni/depth/camera_info</depthImageCameraInfoTopicName>
          <pointCloudTopicName>openni/depth/points</pointCloudTopicName>
          <frameName>openni_depth_optical_frame</frameName>
          <pointCloudCutoff>0.5</pointCloudCutoff>
          <distortionK1>0</distortionK1>
          <distortionK2>0</distortionK2>
          <distortionK3>0</distortionK3>
          <distortionT1>0</distortionT1>
          <distortionT2>0</distortionT2>
          <CxPrime>0</CxPrime>
          <Cx>0</Cx>
          <Cy>0</Cy>
          <focalLength>0</focalLength>
          <hackBaseline>0</hackBaseline>
        </plugin>
      </sensor>
    </gazebo>
    
    <gazebo reference="infrared_frame">
      <sensor type="camera" name="thermal_camera_sensor">
        <update_rate>10</update_rate>
        
        <camera>
          <horizontal_fov>${90.0*M_PI/180.0}</horizontal_fov>
          <image>
            <format>R8G8B8</format>
            <width>160</width>
            <height>120</height>
          </image>
          <clip>
            <near>0.01</near>
            <far>100</far>
          </clip>
        </camera>
        
        <plugin name="thermal_camera_controller" filename="libgazebo_ros_thermal_camera.so">
          <alwaysOn>true</alwaysOn>
          <updateRate>10</updateRate>
          <imageTopicName>/thermal/image</imageTopicName>
          <cameraInfoTopicName>/thermal/camera_info</cameraInfoTopicName>
          <frameName>infrared_optical_frame</frameName>
        </plugin>
      </sensor>
    </gazebo>
    
</robot>
