<?xml version="1.0"?>

<robot name="hector_centaur" xmlns:xacro="http://www.ros.org/wiki/xacro">

  <!-- Included URDF Files -->
  <xacro:include filename="$(find hector_tracked_vehicles_description)/urdf/obelix_ugv_standalone.urdf.xacro" />
  
  
  <joint
    name="base_to_pelvis_joint"
    type="fixed">
    <origin
      xyz="0.0 0 0.3"
      rpy="0 0 0"
       />
    <!--rpy="0.000329950722368627 -3.91151844547536E-19 1.16573417585641E-15"-->
    <parent
      link="base_link" />
    <child
      link="pelvis" />
    <!--
    <axis
      xyz="0 0 1" />
    <xacro:joint_medium_servo_limits_macro lower="${-1.8}" upper="${1.3}"/>
    -->
  </joint>
  
  
  

  <xacro:include filename="$(find thor_mang_description)/urdf/constants.xacro" />

  <!--<xacro:include filename="$(find thor_mang_description)/urdf/thor_mang_simple_mesh_visual_geoms.urdf.xacro.xml" />    -->
  <xacro:include filename="$(find thor_mang_description)/urdf/thor_mang_mesh_visual_geoms.urdf.xacro.xml" />

  <xacro:include filename="$(find thor_mang_description)/urdf/thor_mang_primitive_collision_geoms.urdf.xacro.xml" />
  <!--<xacro:include filename="$(find thor_mang_description)/urdf/thor_mang_mesh_collision_geoms.urdf.xacro.xml" />    -->
  
  <xacro:include filename="$(find thor_mang_description)/urdf/thor_poking_stick.urdf.xacro" />
  <xacro:include filename="$(find thor_mang_description)/urdf/arm/thor_arm_7dof_simple.urdf.xacro" />
  <xacro:include filename="$(find thor_mang_description)/urdf/torso/thor_mang_torso.urdf.xacro.xml" />
  <xacro:include filename="$(find thor_mang_description)/urdf/leg/thor_mang_leg.urdf.xacro.xml" />
  
  
  <xacro:include filename="$(find thor_mang_description)/urdf/head/thor_head_pan_tilt_unit.urdf.xacro.xml" />
  <xacro:include filename="$(find thor_mang_description)/urdf/head/thor_$(optenv THOR_HEAD_TYPE hector_multisensor)_head.urdf.xacro.xml" />
  <xacro:include filename="$(find thor_mang_description)/urdf/lidar/thor_lidar_pan_unit.urdf.xacro.xml" />
  
  <!--<xacro:include filename="$(find thor_mang_description)/robots/offsets/thor_mang_tud_joint_offsets.urdf.xacro.xml" /-->>
  <xacro:include filename="$(find thor_mang_description)/robots/offsets/thor_mang_zero_offsets.urdf.xacro.xml" />     
  
<!--  <macro name="thor_mang_tud_simple_macro">-->
  
  <thor_mang_torso_macro />
  
  <!--  
  <thor_mang_leg_macro parent="pelvis" name="l" reflect="1" leg_joint3_limit_lower="${-M_PI*0.15}" leg_joint3_limit_upper="${M_PI}">
    <origin xyz="0.0 0.072 -0.145" rpy="0 0 0"/>
  </thor_mang_leg_macro>
  
  <thor_mang_leg_macro parent="pelvis" name="r" reflect="-1" leg_joint3_limit_lower="${-M_PI}" leg_joint3_limit_upper="${M_PI*0.15}">
    <origin xyz="0.0 -0.072 -0.145" rpy="0 0 0"/>
  </thor_mang_leg_macro>
  
  <thor_poking_stick_macro parent="utorso">    
    <origin xyz="0.185 0.130 0.224" rpy="0 ${0 + l_arm_j0_offset} 0"/>
  </thor_poking_stick_macro>
  -->
  
   <!-- lower3 -M_PI  upper3 M_PI*0.1 --> <!-- limit_6 could be -M_PI*1.3 -->
  <thor_arm_7dof_simple_with_offsets_macro parent="utorso" name="l" reflect="1"
        
     arm_joint_0_limit_lower="${-M_PI}"
     arm_joint_0_limit_upper="${2.3}"
     arm_joint_1_limit_lower="${-M_PI}"
     arm_joint_1_limit_upper="${0.05}" 
     arm_joint_2_limit_lower="${-M_PI*0.5}"
     arm_joint_2_limit_upper="${M_PI}" 
     arm_joint_3_limit_lower="${-2.9}" 
     arm_joint_3_limit_upper="${0.6}"
     arm_joint_4_limit_lower="${-M_PI}"
     arm_joint_4_limit_upper="${4.71}"  
     arm_joint_5_limit_lower="${-1.47}"   
     arm_joint_5_limit_upper="${1.47}"   
     arm_joint_6_limit_lower="${-2.54}"   
     arm_joint_6_limit_upper="${0.9}"
                           
     j1_offset="${l_arm_j1_offset}"
     j2_offset="${l_arm_j2_offset}"
     j3_offset="${l_arm_j3_offset}"
     j4_offset="${l_arm_j4_offset}"
     j5_offset="${l_arm_j5_offset}"
     j6_offset="${l_arm_j6_offset}">    
    <origin xyz="0.0 0.234 0.165" rpy="0 ${0 + l_arm_j0_offset} 0"/>
  </thor_arm_7dof_simple_with_offsets_macro>
 
  <thor_arm_7dof_simple_with_offsets_macro parent="utorso" name="r" reflect="-1"
     arm_joint_0_limit_lower="${-2.3}"
     arm_joint_0_limit_upper="${M_PI}"
     arm_joint_1_limit_lower="${-0.05}"
     arm_joint_1_limit_upper="${M_PI}" 
     arm_joint_2_limit_lower="${-M_PI}"
     arm_joint_2_limit_upper="${M_PI*0.5}" 
     arm_joint_3_limit_lower="${-0.6}" 
     arm_joint_3_limit_upper="${2.9}"
     arm_joint_4_limit_lower="${-4.71}"
     arm_joint_4_limit_upper="${M_PI}"  
     arm_joint_5_limit_lower="${-1.47}"   
     arm_joint_5_limit_upper="${1.47}"   
     arm_joint_6_limit_lower="${-0.9}"   
     arm_joint_6_limit_upper="${2.54}"

     j1_offset="${r_arm_j1_offset}"
     j2_offset="${r_arm_j2_offset}"
     j3_offset="${r_arm_j3_offset}"
     j4_offset="${r_arm_j4_offset}"
     j5_offset="${r_arm_j5_offset}"
     j6_offset="${r_arm_j6_offset}">    
    <origin xyz="0.0 -0.234 0.165" rpy="0 ${0 + r_arm_j0_offset} 0"/>
  </thor_arm_7dof_simple_with_offsets_macro>
  
  <thor_head_pan_tilt_unit_macro parent="utorso" name="head" head_link_name="head_link"
     j1_offset="${head_j1_offset}">
    <origin xyz="0.0 0.0 0.320" rpy="0 ${0 + head_j0_offset} 0"/>
  </thor_head_pan_tilt_unit_macro>
  
  <thor_head_macro />  
  <!--  
  <thor_lidar_pan_unit_macro parent="utorso" name="waist">
    <origin xyz="0.05 0.0 0.08" rpy="0 0 0"/>
  </thor_lidar_pan_unit_macro>
  -->
  
  <xacro:include filename="$(find thor_mang_description)/hands/$(optenv RIGHT_HAND_TYPE l_vt_hand).urdf.xacro" />
  <xacro:include filename="$(find thor_mang_description)/hands/$(optenv LEFT_HAND_TYPE  r_vt_hand).urdf.xacro" />
  
  <gazebo>
    <plugin name="gazebo_ros_control" filename="libgazebo_ros_control.so">
      <robotNamespace>thor_mang</robotNamespace>
    </plugin>
  </gazebo>
<!--</macro>-->
      
</robot>
